### PR TITLE
V1.1.1 secure

### PR DESCRIPTION
**Pull request by faddat**
Please target this branch with pull requests (team and validators alike)

When this branch passes tests, we can merge it.

### CODE REVIEW

**Review by TheMarstonConnell — COMMENTED** [review]
@faddat you mention not needing third party protos however every reference I can find for generating protos relies on the gogoproto proto in the third party folder. Any resolution to this as we were running it with ignite before?

**Comment by bjaanes** [comment]
@TheMarstonConnell you can use buf dependencies for this. We did this too when we pulled out ignite from empowerchain: https://github.com/empowerchain/empowerchain/blob/main/chain/proto/buf.yaml

**Comment by faddat** [comment]
but why would one ever need to remove ignite?

is it like eject-react-app?

**Comment by faddat** [comment]
This branch is getting too large now.  I've merged in the mint-module branch and I suggest that we open a draft pr for ongoing work that targets `master`.  This way we can make smaller pull requests.

**Review by TheMarstonConnell — APPROVED** [review]

**Pull request merged**
