### PR TITLE
Jkl 144 unit testing access go

### PR DESCRIPTION
**Pull request by dahn510**
added tests to all functions at access.go in filetree module

### CODE REVIEW

**Comment by BiPhan4** [comment]
Hi @dahn510 ,

tree-local-chain was merged into 1.2.0 yesterday. I also currently have an active PR waiting approval to go into 1.2.0.

Could you please:
a) Wait for my JKL 148 PR to get merged into 1.2.0. 
b) Merge updated 1.2.0 into this branch
c) Test filetree's commands locally to make sure they still all work
d) Update this pull request to merge into 1.2.0

Many thanks.

**Review by BiPhan4 — CHANGES_REQUESTED** [review]
Hi @dahn510 ,

tree-local-chain was merged into 1.2.0 yesterday. I also currently have an active PR waiting approval to go into 1.2.0.

Could you please:
a) Wait for my JKL 148 PR to get merged into 1.2.0.
b) Merge updated 1.2.0 into this branch
c) Test filetree's commands locally to make sure they still all work
d) Update this pull request to merge into 1.2.0

Many thanks.

**Review by TheMarstonConnell — CHANGES_REQUESTED** [review]
Can you lint this :)

**Review by TheMarstonConnell — APPROVED** [review]

**Review by nuggetnchill — APPROVED** [review]

**Review by BiPhan4 — APPROVED** [review]
@dahn510 @nuggetnchill @TheMarstonConnell I merged this into 'make-root-test' and ran txs locally--all is fine. Go ahead and merge this PR before I merge 'make-root-test.'

**Pull request merged**
