### PR TITLE
Jkl 161 add read me

### PR DESCRIPTION
**Pull request by BiPhan4**
Please review for accuracy.

### CODE REVIEW

**Comment by TheMarstonConnell** [comment]
@BiPhan4 still need a review on this or did erin look over it?

**Comment by BiPhan4** [comment]
@TheMarstonConnell Erin gave me some feed back on it but never clicked approve. I can wait for him to approve--he's who will be relying on it the most.

**Review by dahn510 — APPROVED** [review]
:+1:

**Comment by BiPhan4** [comment]
@karnthis Ah you've pointed out an inconsistency with protocol buffers and golang standard. The .proto definitions are camel case but the generated class files--.pb.go--class files are use pascal casing. 

The CLI wraps the tx.pb.go class file to use functions that take camelCase arguments, but it does not wrap query.pb.go--PascalCasing. I mistakenly followed the CLI when writing this readMe.

I've changed the readMe to reflect that types as they are defined in their .proto files, the single source of truth across all language implementations. Your APIs compile directly from the .proto files so you're good to go.

@TheMarstonConnell I merged most recently 1.2.0 into this PR just now and pushed my edit to the readMe. Please merge if this PR into 1.2.0 if it all checks out. 

Thank you.

**Comment by BiPhan4** [comment]
@karnthis Fixed it. Thanks for catching that.

**Review by karnthis — APPROVED** [review]

**Pull request merged**
