### PR TITLE
fix

### PR DESCRIPTION
**Pull request by nuggetnchill**
"/jackal-dao/canine-chain/storage/payment_info" doesnt return anything for eddy, do you think this will do the trick?
@TheMarstonConnell

### CODE REVIEW

**Comment by TheMarstonConnell** [comment]
That should only affect the cli, is he using the rpc endpoint?

**Comment by nuggetnchill** [comment]
> That should only affect the cli, is he using the rpc endpoint?

yes he is, not sure if i missed anything when creating the storage payment info

**Comment by TheMarstonConnell** [comment]
No idea in that regard, I somewhat forget what data you're supposed to get back.

**Comment by TheMarstonConnell** [comment]
This won't help eddy but it's a good fix.

**Pull request merged**
